home/urls.py
from django.urls import path
from . import views


app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('advertise/', views.advertise, name='advertise'),
    path('about-us/', views.about, name='about-us'),
    path('promote/', views.promote, name='promote'),
    path('privacy-policy/', views.privacy, name='privacy-policy'),
    path('s/', views.search, name='search')
]

majestylink/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('poem/', include('poems.urls')),
    path('video/', include('video.urls')),
    path('music/', include('music.urls', namespace='music')),
    path('ckeditor/', include('ckeditor_uploader.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/urls.py
from django.urls import path
from . import views

app_name = 'music'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),

    path('<slug:slug>/', views.detail, name='detail'),

]

poems/urls.py
from django.urls import path
from . import views

app_name = 'poem'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),

    path('<slug:slug>/', views.detail, name='detail'),

]

video/urls.py
from django.urls import path
from . import views

app_name = 'video'

urlpatterns = [
    path('', views.videos_list, name='index'),

    path('movies_videos/', views.movies_videos, name='movies_videos'),

    path('music_videos/', views.music_videos, name='music_videos'),
    
    path('<slug:slug>/', views.post_detail, name='detail'),

]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
import random
from music.models import Music
from poems.models import Poem
from video.models import Video
from django.http import HttpResponse
from django.db.models import Count
from django.db.models import Q

def index(request):
	music_list = Music.objects.order_by('uploaded_date')[:5]
	poem_list = Poem.objects.order_by('-uploaded_date')[:3]
	video_list = Video.objects.order_by('-uploaded_date')[:3]
	

	context = {
        'music_list': music_list,
        'poem_list': poem_list,
        'video_list': video_list,
        }



	return render(request, 'home/index.html', context)

def search(request):
	try:
		q = request.GET.get('q')
	except:
		q = None
	if q:
		music_list = Music.objects.filter(Q(title__icontains=q) | Q(artist__icontains=q))
		poem_list = Poem.objects.filter(Q(title__icontains=q) | Q(author__icontains=q) | Q(text__icontains=q))
		video_list = Video.objects.filter(Q(title__icontains=q) | Q(artist__icontains=q))
		context = {'query': q, 'music_list': music_list, 'poem_list': poem_list, 'video_list': video_list}
		template = 'home/results.html'

	else:
		template = 'home/index.html'
		context = {}
	return render(request, template, context)

def about(request):
	return render(request, 'home/about.html')

def privacy(request):
	return render(request, 'home/privacy.html')

def promote(request):
	return render(request, 'home/promote.html')

def advertise(request):
	return render(request, 'home/advertise.html')

home/templates/home/about.html
{% extends "base.html" %}
{% block title %}About Us{% endblock %}

{% block header %}

<div class="container">
	<div class="space"></div>

<h4>About Us</h4>

<p>Welcome to Majesty Empire, your number one source for Nigerian music and videos.</p>

<p>Founded in 2019 by Majesty, Majesty Empire has come a long way from its beginnings.</p>

<p>We hope you enjoy our products as much as we enjoy offering them to you. If you have any questions or comments, please don’t hesitate to contact us.</p>

<p>Sincerely,</p>

<p>Majesty.</p>
<div class="space"></div>

</div>
{% endblock %}

home/templates/home/advertise.html
{% extends "base.html" %}
{% block title %}Advertise{% endblock %}

{% block header %}
<div class="container">
	<div class="space"></div>
	<h4>Advertise</h4>
	<p>Do you have a product that you want to be introduced to our audience, you can advertise on our platform. Contact us via majestylink6@gmail.com for more inquiries.</p>
	<div class="space"></div>
</div>
{% endblock %}

home/templates/home/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}

{% block header %}

<div class="container">
	<div class="firstbreak">
		<p class="trend">Hear what's trending for free</p>
		{% if music_list %}
			<div class="card-deck">
				{% for music in music_list %}
					<div class="card">
						<a href="{% url 'music:detail' music.slug %}">
							<img src="{{ music.thumbnail.url }}" class="card-img-top" alt="...">
						</a>
						<div class="card-body">
							<a href="{% url 'music:detail' music.slug %}" style="color: black">
						  		<h5 class="card-title">{{ music.title }}</h5>
						  	</a>
						</div>
						  <p class="card-text"><small class="text-muted">{{music.artist}}</small></p>
					</div>
				{% endfor %}
			</div>

			<div class="explore-btn">
				<a href="\music">Explore more</a>
			</div>
		{% endif %}
	</div>

	<div class="secondbreak">

		<p class="trend">Keep up with your latest movies and music videos</p>

		{% if video_list %}

		<div class="card-deck">
			{% for video in video_list %}
				<div class="card">
					<a href="{% url 'video:detail' video.slug %}">
						<img src="{{ video.thumbnail.url }}" class="card-img-top" alt="...">
					</a>
					<div class="card-body">
						<a href="{% url 'video:detail' video.slug %}" style="color: black">
					  		<h5 class="card-title">{{ video.title }}</h5>
					  	</a>
					</div>
					  <p class="card-text"><small class="text-muted">Video Category: {{video.category}}</small></p>
				</div>
			{% endfor %}
		</div>

		<div class="explore-btn">
			<a href="\video">More</a>
		</div>
		{% endif %}
	</div>

	<div class="thirdbreak">
		<p class="trend">Featured Poems</p>
		{% if poem_list %}
		<div class="row">		
			{% for poem in poem_list %}
				<div class="col-sm-6 col-lg-4">
				  <div class="card mb-3" style="max-width: 540px;">
					<div class="row no-gutters">
						<div class="col-md-4">
							<img src="{{ poem.thumbnail.url }}" class="card-img" alt="...">
						</div>
						<div class="col-md-1"></div>
						<div class="col-md-7">
							<div class="card-body">
								<h2 class="card-title-poem">{{poem.title}}</h2>
								<p class="card-text-poem">By{{poem.author}}</p>
								<p>{{poem.text | truncatewords:20 | safe}}</p>
								<a class="poemlink" href="{% url 'poem:detail' poem.slug %}">Read More</a>
							</div>
						</div>
				    </div>
				  </div>
				</div>
			{% endfor %}

		</div>

		<div class="explore-btn">
			<a href="\poem">Browse all poems</a>
		</div>
		{% endif %}
	</div>
</div>

{% endblock %}

home/templates/home/privacy.html
{% extends "base.html" %}
{% block title %}Promote{% endblock %}

{% block header %}

<div class="container">
	<div class="space"></div>
<h4>Privacy Policy</h4>

<p>At Majestylink, accessible from https://www.majestylink.com, one of our main priorities is the privacy of our visitors. This Privacy Policy document contains types of information that is collected and recorded by Majestylink and how we use it.</p>

<p>If you have additional questions or require more information about our Privacy Policy, do not hesitate to contact us.</p>

<h4>Log Files</h4>

<p>Majestylink follows a standard procedure of using log files. These files log visitors when they visit websites. All hosting companies do this and a part of hosting services’ analytics. The information collected by log files include internet protocol (IP) addresses, browser type, Internet Service Provider (ISP), date and time stamp, referring/exit pages, and possibly the number of clicks. These are not linked to any information that is personally identifiable. The purpose of the information is for analyzing trends, administering the site, tracking users’ movement on the website, and gathering demographic information.</p>

<h4>Google DoubleClick DART Cookie</h4>

<p>Google is one of a third-party vendor on our site. It also uses cookies, known as DART cookies, to serve ads to our site visitors based upon their visit to www.website.com and other sites on the internet. However, visitors may choose to decline the use of DART cookies by visiting the Google ad and content network Privacy Policy at the following URL – https://policies.google.com/technologies/ads</p>

<h4>Our Advertising Partners</h4>

<p>Some of advertisers on our site may use cookies and web beacons. Our advertising partners are listed below. Each of our advertising partners has their own Privacy Policy for their policies on user data. For easier access, we hyperlinked to their <a href="Googlehttps://policies.google.com/technologies/ads">Privacy Policies.</a></p>

    

<h4>Online Privacy Policy Only</h4>

<p>This Privacy Policy applies only to our online activities and is valid for visitors to our website with regards to the information that they shared and/or collect in Majestylink. This policy is not applicable to any information collected offline or via channels other than this website.
Consent</p>

<p>By using our website, you hereby consent to our Privacy Policy and agree to its Terms and Conditions.</p>
<div class="space"></div>
</div>
{% endblock %}

home/templates/home/promote.html
{% extends "base.html" %}
{% block title %}Promote{% endblock %}

{% block header %}
<div class="container">
	<div class="space"></div>
	<h4>Promote Music/Video</h4>
	<p>Do you have a new song, album or mixtape and want us to help you get it across a large audience? Contact us via our handles below.</p>
	<div class="space"></div>
</div>
{% endblock %}

home/templates/home/results.html
{% extends "base.html" %}
{% block title %}Search results for "{{query}}"{% endblock %}

{% block header %}
<div class="container">
	<h5>Search results for "{{query}}"</h5>
	{% if music_list or video_list or poem_list %}
		{% if music_list %}
			<div class="blocktitle">Music</div>
			{% for music in music_list %}
					<div class="search">
						<a href="{% url 'music:detail' music.slug %}">
							<img src="{{ music.thumbnail.url }}" class="card-img-top" alt="...">
						</a>
						<div class="card-body">
							<a href="{% url 'music:detail' music.slug %}" style="color: black">
						  		<h5 class="card-title">{{ music.title }}</h5>
						  	</a>
						</div>
						  <p class="card-text"><small class="text-muted">{{music.artist}}</small></p>
					</div>
					<hr>
			{% endfor %}
		{% endif %}
		{% if video_list %}
			<div class="blocktitle">Music</div>
			{% for video in video_list %}
					<div class="search">
						<a href="{% url 'video:detail' video.slug %}">
							<img src="{{ video.thumbnail.url }}" class="card-img-top" alt="...">
						</a>
						<div class="card-body">
							<a href="{% url 'video:detail' video.slug %}" style="color: black">
						  		<h5 class="card-title">{{ video.title }}</h5>
						  	</a>
						</div>
						  <p class="card-text"><small class="text-muted">Video Category: {{video.category}}</small></p>
					</div>
				{% endfor %}
		{% endif %}
		{% if poem_list %}
			<div class="blocktitle">Poem</div>
			{% for poem in poem_list %}
				<div class="search">
					<a href="{% url 'poem:detail' poem.slug %}">
						<img src="{{ poem.thumbnail.url }}" class="card-img-top" alt="...">
					</a>
					<div class="card-body">
						<a href="{% url 'poem:detail' poem.slug %}" style="color: black">
					  		<h5 class="card-title">{{ poem.title }}</h5>
					  	</a>
					</div>
					  <p class="card-text"><small class="text-muted">{{poem.author}}</small></p>
				</div>
				<hr>
			{% endfor %}
		{% endif %}
	{% else %}
	<h6>No entries for "{{query}}"</h6>
	<div class="space"></div>
	{% endif %}
</div>

{% endblock %}